<?php

/**
 * Created by PhpStorm.
 * User: carlo
 * Date: 15/06/17
 * Time: 13.36
 */
class FServizio extends FDb
{
    /**
     * FServizio constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * @string $codice
     * @return array
     */
    public function searchByCodice($codice)
    {
        $this->sql = $this->con->prepare("SELECT *
                      FROM Servizio WHERE codice=?");

        return parent::searchById(array($codice)); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function searchAll()
    {
        $this->sql = $this->con->prepare("SELECT *
                      FROM Servizio");
        return parent::searchAll();
    }

    /**
     * @string $nomeCategoria
     * @return array
     */
    public function searchByCategoria($nomeCategoria)
    {
        $this->sql = $this->con->prepare("SELECT *
                      FROM Servizio
                      WHERE categoria = ?");
        return parent::search(array($nomeCategoria));
    }

    /**
     * @string $nomeServizio
     * @string $prezzoServizio
     * @return array
     */
    public function searchByNomePrezzo($nomeServizio, $prezzoServizio)
    {
        $this->sql = $this->con->prepare("SELECT *
                      FROM Servizio
                      WHERE nome = ? AND  prezzo = ?");
        return parent::searchById(array($nomeServizio, $prezzoServizio));
    }

    /**
     * @string $nome
     * @string $descrizione
     * @float $prezzo
     * @int $durata
     * @string $codice
     */
    public function insert($nome, $descrizione, $prezzo, $durata, $categoria)
    {
        $this->sql =
            $this->con->prepare("INSERT INTO Servizio(nome, descrizione, prezzo, durata, categoria)
                                 VALUES (?,?,?,?,?)");
        return parent::query(array($nome, $descrizione, $prezzo, $durata, $categoria));

    }

    /**
     * @int $codice
     * @string $nome
     * @string $descrizione
     * @float $prezzo
     * @int $durata
     * @string $codice
     */
    public function update($codice, $nome, $descrizione, $prezzo, $durata, $categoria)
    {
        $this->sql = $this->con->prepare("UPDATE Servizio
                     SET nome = ?,
                         descrizione = ?,
                         prezzo = ?,
                         durata = ?,
                         categoria = ?
                     WHERE codice = ?;");
        parent::query(array($nome, $descrizione, $prezzo, $durata, $categoria, $codice));
    }

    /**
     * @string $nome
     * @string $descrizione
     * @float $prezzo
     * @int $durata
     * @string $codice
     */
    public function updateAttributi($nome, $descrizione, $prezzo, $durata, $codice)
    {
        $this->sql = $this->con->prepare("UPDATE Servizio
                     SET nome = ?,
                         descrizione = ?,
                         prezzo = ?,
                         durata = ?
                     WHERE codice = ?;");
        parent::query(array($nome, $descrizione, $prezzo, $durata, $codice));
    }

    /**
     * @string $nomeVecchioCategoria: è il nome vecchio della categoria
     * @string $nomeNuovoCategoria: è il nome nuovo della categoria
     */
    public function updateCategoria($nomeVecchioCategoria, $nomeNuovoCategoria)
    {
        $this->sql = $this->con->prepare("UPDATE Servizio
                     SET categoria = ?
                     WHERE categoria = ?;");
        parent::query(array($nomeVecchioCategoria, $nomeNuovoCategoria));
    }

    /**
     * @string $codice
     */
    public function delete($codice)
    {
        $this->sql = $this->con->prepare("DELETE FROM Servizio WHERE codice = ?;");
        parent::query(array($codice));
    }

}